[PRIMA-7248]: Refactor drone.yml and build scripts with multiple countries support
primait/telepoison pull request #4
Opened 2021-02-23 13:50 UTC by oleksandr-gubchenko

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-7248 

 ^

2021-02-23 16:24 UTC, made2591 submitted a review, later dismissed
LGTM

2021-02-23 16:41 UTC, larrywax requested changes
Solo una cosina da fixare

2021-02-23 16:41 UTC, larrywax commented on deploy/build
> +aws --region="eu-west-1" s3 cp "${VERSION}"-"${ENV}".tar.gz s3://prima-artifacts-encrypted/microservices/telepoison/"${VERSION}"-"${ENV}".tar.gz
Questo non mi torna, non esiste `"${VERSION}"-"${ENV}".tar.gz` 
Non mi ricordo però se questa linea la aggiunge di base qualche template

2021-02-24 08:06 UTC, larrywax submitted a review, later dismissed

2021-02-24 09:02 UTC, merged